---
- name: Setup Arch Linux with pacman packages and curl installations
  hosts: localhost
  
  vars_files:
    - pacman.yml
    - curl.yml
    - sudo-curl.yml
    - go.yml
  
  tasks:
    - name: Update package cache and upgrade all packages
      become: true
      community.general.pacman:
        update_cache: yes
        upgrade: yes
      register: upgrade_result
      tags: 
        - update
        - pacman
        - curl
        - go
        - git
        - cni
        - oh-my-zsh
      
    - name: Display upgrade results
      debug:
        msg: "Upgraded packages: {{ upgrade_result.stdout_lines | default('No output') }}"
      tags:
        - update
        
    - name: Install specified packages with pacman
      become: true
      community.general.pacman:
        name: "{{ packages }}"
        state: present
      register: install_result
      tags:
        - pacman
      
    - name: Display installation results
      debug:
        msg: "Installed packages: {{ install_result.stdout_lines | default('No output') }}"
      tags:
        - pacman
    
    - name: Run curl installations
      shell: "{{ item }}"
      loop: "{{ curl_commands }}"
      tags:
        - curl

    - name: Run sudo curl installations
      become: true
      shell: "{{ item }}"
      loop: "{{ sudo_curl_commands }}"
      tags:
        - curl


    - name: Install Go packages
      shell: "go install {{ item }}"
      loop: "{{ go_packages }}"
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/go/bin"
      register: go_install_result
      tags:
        - go

    - import_tasks: git.yml
      tags:
        - git

    - import_tasks: cni-plugins.yml
      tags:
       - cni

    - import_tasks: oh-my-zsh.yml
      tags:
       - oh-my-zsh

    - import_tasks: rust-cargo.yml
      tags:
        - cargo
